//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Examples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Calculator {
            get {
                object obj = ResourceManager.GetObject("Calculator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uniform mat4 objMat;
        ///uniform mat4 viewMat;
        ///uniform mat4 projMat;
        ///uniform sampler2D bumpTxt;
        ///uniform float offsetScalar;
        ///
        ///attribute vec3 posAttr;
        ///attribute vec3 normAttr;
        ///attribute vec3 binmAttr;
        ///attribute vec2 txtAttr;
        ///attribute float weightAttr;
        ///
        ///varying vec3 color;
        ///
        ///vec3 bumpyNormal(vec3 color)
        ///{
        ///   vec3 n = normalize(objMat*vec4(normAttr, 0.0)).xyz;
        ///   vec3 b = normalize(objMat*vec4(binmAttr, 0.0)).xyz;
        ///   vec3 c = cross(b, n);
        ///   b = cross(n, c);
        ///   mat3 mat = mat3( b.x,  b.y,  b.z,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GlslExample {
            get {
                return ResourceManager.GetString("GlslExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GlslLang {
            get {
                object obj = ResourceManager.GetObject("GlslLang", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
